
package com.lexmark.workflow.components.prompt.jsapi2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JobSubmission2", targetNamespace = "http://jsapi2.prompt.components.workflow.lexmark.com/", wsdlLocation = "file:/C:/Users/Who_Is_Stopping_You/Desktop/wsdl/waebAxis/JobSubmission2.wsdl")
public class JobSubmission2
    extends Service
{

    private final static URL JOBSUBMISSION2_WSDL_LOCATION;
    private final static WebServiceException JOBSUBMISSION2_EXCEPTION;
    private final static QName JOBSUBMISSION2_QNAME = new QName("http://jsapi2.prompt.components.workflow.lexmark.com/", "JobSubmission2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7001/webAxis2Job/services/JobSubmission2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JOBSUBMISSION2_WSDL_LOCATION = url;
        JOBSUBMISSION2_EXCEPTION = e;
    }

    public JobSubmission2() {
        super(__getWsdlLocation(), JOBSUBMISSION2_QNAME);
    }

   /* public JobSubmission2(WebServiceFeature... features) {
        super(__getWsdlLocation(), JOBSUBMISSION2_QNAME, features);
    }

    public JobSubmission2(URL wsdlLocation) {
        super(wsdlLocation, JOBSUBMISSION2_QNAME);
    }

    public JobSubmission2(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JOBSUBMISSION2_QNAME, features);
    }

    public JobSubmission2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JobSubmission2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }
*/
    /**
     * 
     * @return
     *     returns JobSubmission2PortType
     */
    @WebEndpoint(name = "JobSubmission2SOAP11port_http")
    public JobSubmission2PortType getJobSubmission2SOAP11PortHttp() {
        return super.getPort(new QName("http://jsapi2.prompt.components.workflow.lexmark.com/", "JobSubmission2SOAP11port_http"), JobSubmission2PortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JobSubmission2PortType
     */
    @WebEndpoint(name = "JobSubmission2SOAP11port_http")
    public JobSubmission2PortType getJobSubmission2SOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://jsapi2.prompt.components.workflow.lexmark.com/", "JobSubmission2SOAP11port_http"), JobSubmission2PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JOBSUBMISSION2_EXCEPTION!= null) {
            throw JOBSUBMISSION2_EXCEPTION;
        }
        return JOBSUBMISSION2_WSDL_LOCATION;
    }

}
