
package com.lexmark.workflow.components.prompt.jsapi2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JobSubmission2PortType", targetNamespace = "http://jsapi2.prompt.components.workflow.lexmark.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JobSubmission2PortType {


    /**
     * 
     * @param part1
     * @return
     *     returns com.lexmark.workflow.components.prompt.jsapi2.JobSubmissionOutput
     * @throws ProfileNotFoundFault
     */
    @WebMethod(action = "submitJob")
    @WebResult(name = "JobSubmissionResponse", targetNamespace = "http://jsapi2.prompt.components.workflow.lexmark.com/", partName = "part1")
    public JobSubmissionOutput submitJob(
        @WebParam(name = "JobSubmissionRequest", targetNamespace = "http://jsapi2.prompt.components.workflow.lexmark.com/", partName = "part1")
        JobSubmissionInput part1)
        throws ProfileNotFoundFault
    ;

}
